apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tn-openbsw-openzaak
namePrefix: openzaak-

buildMetadata: [originAnnotations]

resources:
- manifests/postgres/
- manifests/mailcatcher/
- manifests/redis/
- manifests/openzaak/

