apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openzaak-open-zaak
  labels:
    
    app.kubernetes.io/version: "1.6.0"
    helm.sh/chart: open-zaak-0.8.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: open-zaak
    app.kubernetes.io/instance: openzaak
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 1Gi