apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.3

  bootstrap:
    initdb:
      database: openzaak
      owner: openzaak
      secret:
        name: openzaak-postgres-sec
      # postInitSQL:
      #   - CREATE EXTENSION IF NOT EXISTS postgis;
      #   - CREATE EXTENSION IF NOT EXISTS pg_trgm;

  storage:
    storageClass: managed-csi-premium
    size: 2Gi

  enableSuperuserAccess: true
  superuserSecret:
    name: openzaak-postgres-sec-super

  postgresql:
    parameters:
      shared_buffers: "128MB"

  resources:
    requests:
      memory: "1Gi"
      cpu: "100m"
